apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels: { app: my-app }
  template:
    metadata: { labels: { app: my-app } }
    spec:
      containers:
      - name: my-app
        image: 3.113.20.47.sslip.io:5000/rancher/nginx:1.26.0  # {"$imagescan":"test-scan"}
        ports: [{ containerPort: 80 }]
